[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[target.riscv32imafc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = "riscv32imafc-unknown-none-elf"
