[package]
name = "emulator_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
crossterm = "0.27"
ratatui = "0.26"
tracing = "0.1"
tracing-subscriber = "0.3"
emulator_core = { path = "../core" }
