control_points = [
  [-111.9763, -299.5179],
  [-118.7894, -299.3856],
  [-121.8982, -298.2612],
  [-124.1472, -295.483],
  [-125.0732, -290.7205],
  [-127.719, -279.0789],
  [-135.1935, -257.383],
  [-152.40789999999998, -211.3947],
  [-166.43959999999998, -175.8478],
  [-175.6069, -150.4038],
  [-186.458, -111.3023],
  [-194.877, -72.20070000000001],
  [-203.1089, -21.686800000000005],
  [-209.8441, 20.595299999999995],
  [-220.13400000000001, 54.0841],
  [-236.6913, 90.4729],
  [-253.0616, 118.7466],
  [-276.07349999999997, 158.94729999999998],
  [-288.0472, 178.77870000000001],
  [-292.4222, 186.75310000000002],
  [-292.81899999999996, 191.1187],
  [-291.0992, 194.52530000000002],
  [-288.1888, 196.245],
  [-283.8893, 196.5096],
  [-276.3818, 195.61669999999998],
  [-238.2487, 189.89499999999998],
  [-214.9654, 184.6034],
  [-187.9779, 176.7982],
  [-160.4612, 167.1409],
  [-114.556, 145.7096],
  [-69.5769, 123.6169],
  [-6.870599999999996, 94.3805],
  [30.171099999999996, 80.093],
  [76.20859999999999, 65.01169999999999],
  [117.982, 52.9148],
  [124.34299999999999, 49.8746],
  [128.2718, 44.4023],
  [129.7686, 38.6961],
  [129.675, 32.9431],
  [127.4299, 27.1434],
  [120.83500000000001, 21.296800000000005],
  [104.0906, 7.826400000000007],
  [90.1525, -0.4989999999999952],
  [72.94030000000001, -6.485799999999998],
  [49.4607, -11.1631],
  [27.6181, -10.180800000000005],
  [11.9148, -7.351799999999997],
  [-6.341399999999993, -1.2664000000000044],
  [-54.7602, 20.826300000000003],
  [-86.5102, 34.849199999999996],
  [-96.4982, 37.0982],
  [-107.4123, 36.3044],
  [-116.0774, 34.2539],
  [-125.6024, 29.293000000000006],
  [-132.1508, 23.6044],
  [-138.7654, 14.410200000000003],
  [-142.99869999999999, 4.3559999999999945],
  [-144.5201, -5.8966000000000065],
  [-142.6019, -20.713300000000004],
  [-128.4456, -72.4941],
  [-123.8769, -91.65799999999999],
  [-121.2109, -101.3398],
  [-118.0771, -107.46690000000001],
  [-113.2128, -114.2021],
  [-106.8986, -120.32929999999999],
  [-97.5909, -125.3339],
  [-86.693, -127.9999],
  [-76.5435, -127.90639999999999],
  [-64.7569, -125.8484],
  [-54.3734, -119.44059999999999],
  [-43.6159, -110.64750000000001],
  [-33.513099999999994, -103.351],
  [-20.136200000000002, -97.1771],
  [-7.414199999999994, -93.3418],
  [5.214299999999994, -91.5644],
  [21.397499999999994, -90.90960000000001],
  [33.37110000000001, -92.31280000000001],
  [61.340900000000005, -98.86089999999999],
  [247.7908, -145.0675],
  [280.4007, -153.0711],
  [289.8596, -157.37060000000002],
  [298.2601, -165.4404],
  [302.9564, -172.7826],
  [306.1976, -183.63049999999998],
  [306.8591, -192.7586],
  [307.4544, -228.87419999999997],
  [308.9096, -268.3633],
  [308.1158, -275.9701],
  [305.9992, -281.1956],
  [301.369, -284.1722],
  [286.5021, -289.4107],
  [257.6904, -295.3975],
  [234.1173, -298.2039],
  [131.1843, -299.279]
]

[metadata]
name = "Spielberg (Red Bull Ring)"
author = ""
track_width = 12.0
kerb_width = 0.5
